"""Deterministic limits used by LocalCoder's local tools."""

READ_FILE_MAX_LINES = 200
LIST_FILES_MAX_ENTRIES = 500
SEARCH_MAX_MATCHES = 100
MAX_TOOL_OUTPUT_CHARS = 12_000
MAX_WRITE_FILE_CHARS = 1_000_000
DEFAULT_COMMAND_TIMEOUT_SECONDS = 30
MAX_COMMAND_TIMEOUT_SECONDS = 60
